multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/coding/times.py", line 319, in decode_cf_datetime
    dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/coding/times.py", line 247, in _decode_datetime_with_pandas
    raise OutOfBoundsDatetime(
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Cannot decode times from a non-standard calendar, 'noleap', using pandas.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/main_MOASMO_Derecho_part2.5_optional_evaluate.py", line 127, in run_trial
    mo_evaluate_return_many_metrics(outfile_metric, infilelist, fsurdat, date_start, date_end, ref_streamflow, add_flow_file)
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/mo_evaluation.py", line 197, in mo_evaluate_return_many_metrics
    ds_simu = main_read_CTSM_streamflow(fsurdat, CTSMfilelist, date_start, date_end, clm_q_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/mo_evaluation.py", line 80, in main_read_CTSM_streamflow
    ds_simu = xr.open_mfdataset(CTSMfilelist)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/api.py", line 1025, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/api.py", line 1025, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/api.py", line 572, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 607, in open_dataset
    ds = store_entrypoint.open_dataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/store.py", line 58, in open_dataset
    ds = Dataset(vars, attrs=attrs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/dataset.py", line 701, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
                                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/dataset.py", line 430, in merge_data_and_coords
    return merge_core(
           ^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/merge.py", line 718, in merge_core
    collected = collect_variables_and_indexes(aligned, indexes=indexes)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/merge.py", line 358, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/variable.py", line 159, in as_variable
    obj = obj.to_index_variable()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/variable.py", line 572, in to_index_variable
    return IndexVariable(
           ^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/variable.py", line 2641, in __init__
    self._data = PandasIndexingAdapter(self._data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexing.py", line 1481, in __init__
    self.array = safe_cast_to_index(array)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexes.py", line 469, in safe_cast_to_index
    index = pd.Index(np.asarray(array), **kwargs)
                     ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexing.py", line 474, in __array__
    return np.asarray(self.get_duck_array(), dtype=dtype)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexing.py", line 560, in get_duck_array
    array = array.get_duck_array()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/coding/variables.py", line 74, in get_duck_array
    return self.func(self.array.get_duck_array())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/coding/times.py", line 326, in decode_cf_datetime
    dates[np.nanargmin(num_dates)].year < 1678
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/numpy/lib/nanfunctions.py", line 552, in nanargmin
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/main_MOASMO_Derecho_part2.5_optional_evaluate.py", line 151, in <module>
    pool.map(run_trial, tasks)
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/main_MOASMO_Derecho_part2.5_optional_evaluate.py", line 127, in run_trial
    mo_evaluate_return_many_metrics(outfile_metric, infilelist, fsurdat, date_start, date_end, ref_streamflow, add_flow_file)
^^^^^^^^^^^^^^^
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/mo_evaluation.py", line 197, in mo_evaluate_return_many_metrics
    ds_simu = main_read_CTSM_streamflow(fsurdat, CTSMfilelist, date_start, date_end, clm_q_name)
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/home/guoqiang/CTSM_repos/CTSM_calibration/src/MOASMO_support/mo_evaluation.py", line 80, in main_read_CTSM_streamflow
    ds_simu = xr.open_mfdataset(CTSMfilelist)
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/api.py", line 1025, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/api.py", line 1025, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/api.py", line 572, in open_dataset
    backend_ds = backend.open_dataset(
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 607, in open_dataset
    ds = store_entrypoint.open_dataset(
^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/backends/store.py", line 58, in open_dataset
    ds = Dataset(vars, attrs=attrs)
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/dataset.py", line 701, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/dataset.py", line 430, in merge_data_and_coords
    return merge_core(
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/merge.py", line 718, in merge_core
    collected = collect_variables_and_indexes(aligned, indexes=indexes)
      ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/merge.py", line 358, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/variable.py", line 159, in as_variable
    obj = obj.to_index_variable()
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/variable.py", line 572, in to_index_variable
    return IndexVariable(
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/variable.py", line 2641, in __init__
    self._data = PandasIndexingAdapter(self._data)
^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexing.py", line 1481, in __init__
    self.array = safe_cast_to_index(array)
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexes.py", line 469, in safe_cast_to_index
    index = pd.Index(np.asarray(array), **kwargs)
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexing.py", line 474, in __array__
    return np.asarray(self.get_duck_array(), dtype=dtype)
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/core/indexing.py", line 560, in get_duck_array
    array = array.get_duck_array()
^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/coding/variables.py", line 74, in get_duck_array
    return self.func(self.array.get_duck_array())
  ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/xarray/coding/times.py", line 326, in decode_cf_datetime
    dates[np.nanargmin(num_dates)].year < 1678
^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/numpy/lib/nanfunctions.py", line 552, in nanargmin
    raise ValueError("All-NaN slice encountered")
^^^^^^^^^^^^^^^
ValueError: All-NaN slice encountered
